openapi: 3.0.0
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user registration and authentication

servers:
  - url: http://localhost:8080/api
    description: Local development server

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  description: Unique username
                email:
                  type: string
                  format: email
                  description: Unique email address
                password:
                  type: string
                  format: password
                  description: Password (minimum 6 characters)
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
        '500':
          description: Server error

  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  format: password
                  description: Password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      email:
                        type: string
        '401':
          description: Invalid credentials
        '400':
          description: Invalid input 